version: "3"

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  lb:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/lb.conf:/etc/nginx/nginx.conf
