import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-3 p-4 m-2 text-xl font-bold">
          <a href={"/product"}>Product</a>
          <a href={"/project"}>Project</a>
          <a href={"/product/about"}>Product About</a>
          <a href={"/project/about"}>Project About</a>
          <a href={"/product/about/1234"}>Product About with ID</a>
          <a href={"/project/about/4567"}>Project About with ID</a>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
